project: 
  type: website
  output-dir: docs

website: 
  title: "AIML4OS"
  favicon: images/favicon.png
  navbar: 
    logo: images/aiml_logo.png
    title: false
    left:
    - text: "Home"
      href: index.qmd
    - text: "Workpackages"
      menu:
        - text: "Coordination"
          href: project-coordination.qmd
        - text: "Communication"
          href: community-engagement.qmd
        - text: "AI/ML Lab"
          href: aiml-lab.qmd
        - text: "Ecosystem Monitoring"
          href: aiml-ecosystem.qmd
        - text: "Standards, Methodology, Implementation"
          href: methodological-standards.qmd
        - text: "Knowledge Repository"
          href: knowledge-training.qmd
        - text: "Earth Observation Data"
          href: earth-observation.qmd
        - text: "Editing"
          href: statistical-editing.qmd
        - text: "Imputation"
          href: statistical-imputation.qmd
        - text: "Text to Code"
          href: text-classification.qmd
        - text: "Supply Chain Networks"
          href: supply-chain-estimation.qmd
        - text: "LLMs"
          href: large-language-models.qmd 
        - text: "Synthetic Data"
          href: synthetic-data.qmd 
    - text: "News"
      href: news.qmd
    - text: "Deliverables & Tasks"
      href: deliverables-tasks.qmd
    - text: "Consortium"
      href: about-project.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/company/essnet-aiml4os
        text: AIML4OS on LinkedIn
      - icon: github
        href: https://github.com/aiml4os
        text: AIML4OS GitHub
  page-footer: 
    center: 
      - icon: github
        href: https://github.com/aiml4os
      - icon: linkedin 
        href: https://www.linkedin.com/company/essnet-aiml4os

format: 
  html:
    css: styles.css
    toc: false
    


  